--------------------------------------------------------
-- CIMS SCHEMA  
-- DROP TABLES
-- JULY 10, 2013
--------------------------------------------------------
DROP TABLE CCIConceptComponent CASCADE CONSTRAINTS;

DROP TABLE CCIComponentOrAttribute CASCADE CONSTRAINTS;

DROP TABLE CCIConcept CASCADE CONSTRAINTS;

DROP TABLE URLProperty CASCADE CONSTRAINTS;

DROP TABLE StructureElement CASCADE CONSTRAINTS;

DROP TABLE OtherProperty CASCADE CONSTRAINTS;

DROP TABLE DateTimeProperty CASCADE CONSTRAINTS;

DROP TABLE XMLProperty CASCADE CONSTRAINTS;

DROP TABLE TextProperty CASCADE CONSTRAINTS;

DROP TABLE GraphicsProperty CASCADE CONSTRAINTS;

DROP TABLE EnumerationPropertyValue CASCADE CONSTRAINTS;

DROP TABLE Enumeration CASCADE CONSTRAINTS;

DROP TABLE Language CASCADE CONSTRAINTS;

DROP TABLE Specialization CASCADE CONSTRAINTS;

DROP TABLE Concept CASCADE CONSTRAINTS;

DROP TABLE ConceptProperty CASCADE CONSTRAINTS;

DROP TABLE Structure CASCADE CONSTRAINTS;

DROP TABLE ElementVersion CASCADE CONSTRAINTS;

DROP TABLE ValidationRule CASCADE CONSTRAINTS;

DROP TABLE NumericProperty CASCADE CONSTRAINTS;

DROP TABLE Property CASCADE CONSTRAINTS;

DROP TABLE Element CASCADE CONSTRAINTS;

DROP TABLE Class CASCADE CONSTRAINTS;

DROP TABLE DataProperty CASCADE CONSTRAINTS;

DROP TABLE EnumeratedProperty CASCADE CONSTRAINTS;

DROP TABLE ValueDomain CASCADE CONSTRAINTS;

DROP TABLE PropertyCategory CASCADE CONSTRAINTS;


