//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.06 at 06:40:12 PM PDT 
//


package org.cihi.claml.schema;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Meta" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Identifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Title" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Authors" minOccurs="0"/>
 *         &lt;element ref="{}Variants" minOccurs="0"/>
 *         &lt;element ref="{}ClassKinds"/>
 *         &lt;element ref="{}UsageKinds" minOccurs="0"/>
 *         &lt;element ref="{}RubricKinds"/>
 *         &lt;element ref="{}Modifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ModifierClass" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Class" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang use="required""/>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}space default="default""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "meta",
    "identifier",
    "title",
    "authors",
    "variants",
    "classKinds",
    "usageKinds",
    "rubricKinds",
    "modifier",
    "modifierClass",
    "clazz"
})
@XmlRootElement(name = "Classification")
public class Classification {

    @XmlElement(name = "Meta")
    protected List<Meta> meta;
    @XmlElement(name = "Identifier")
    protected List<Identifier> identifier;
    @XmlElement(name = "Title", required = true)
    protected List<Title> title;
    @XmlElement(name = "Authors")
    protected Authors authors;
    @XmlElement(name = "Variants")
    protected Variants variants;
    @XmlElement(name = "ClassKinds", required = true)
    protected ClassKinds classKinds;
    @XmlElement(name = "UsageKinds")
    protected UsageKinds usageKinds;
    @XmlElement(name = "RubricKinds", required = true)
    protected RubricKinds rubricKinds;
    @XmlElement(name = "Modifier")
    protected List<Modifier> modifier;
    @XmlElement(name = "ModifierClass")
    protected List<ModifierClass> modifierClass;
    @XmlElement(name = "Class")
    protected List<Class> clazz;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace", required = true)
    protected String lang;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space;

    /**
     * Gets the value of the meta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Meta }
     * 
     * 
     */
    public List<Meta> getMeta() {
        if (meta == null) {
            meta = new ArrayList<Meta>();
        }
        return this.meta;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Identifier }
     * 
     * 
     */
    public List<Identifier> getIdentifier() {
        if (identifier == null) {
            identifier = new ArrayList<Identifier>();
        }
        return this.identifier;
    }

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Title }
     * 
     * 
     */
    public List<Title> getTitle() {
        if (title == null) {
            title = new ArrayList<Title>();
        }
        return this.title;
    }

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link Authors }
     *     
     */
    public Authors getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authors }
     *     
     */
    public void setAuthors(Authors value) {
        this.authors = value;
    }

    /**
     * Gets the value of the variants property.
     * 
     * @return
     *     possible object is
     *     {@link Variants }
     *     
     */
    public Variants getVariants() {
        return variants;
    }

    /**
     * Sets the value of the variants property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variants }
     *     
     */
    public void setVariants(Variants value) {
        this.variants = value;
    }

    /**
     * Gets the value of the classKinds property.
     * 
     * @return
     *     possible object is
     *     {@link ClassKinds }
     *     
     */
    public ClassKinds getClassKinds() {
        return classKinds;
    }

    /**
     * Sets the value of the classKinds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassKinds }
     *     
     */
    public void setClassKinds(ClassKinds value) {
        this.classKinds = value;
    }

    /**
     * Gets the value of the usageKinds property.
     * 
     * @return
     *     possible object is
     *     {@link UsageKinds }
     *     
     */
    public UsageKinds getUsageKinds() {
        return usageKinds;
    }

    /**
     * Sets the value of the usageKinds property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsageKinds }
     *     
     */
    public void setUsageKinds(UsageKinds value) {
        this.usageKinds = value;
    }

    /**
     * Gets the value of the rubricKinds property.
     * 
     * @return
     *     possible object is
     *     {@link RubricKinds }
     *     
     */
    public RubricKinds getRubricKinds() {
        return rubricKinds;
    }

    /**
     * Sets the value of the rubricKinds property.
     * 
     * @param value
     *     allowed object is
     *     {@link RubricKinds }
     *     
     */
    public void setRubricKinds(RubricKinds value) {
        this.rubricKinds = value;
    }

    /**
     * Gets the value of the modifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Modifier }
     * 
     * 
     */
    public List<Modifier> getModifier() {
        if (modifier == null) {
            modifier = new ArrayList<Modifier>();
        }
        return this.modifier;
    }

    /**
     * Gets the value of the modifierClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modifierClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModifierClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModifierClass }
     * 
     * 
     */
    public List<ModifierClass> getModifierClass() {
        if (modifierClass == null) {
            modifierClass = new ArrayList<ModifierClass>();
        }
        return this.modifierClass;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clazz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClazz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.Class }
     * 
     * 
     */
    public List<Class> getClazz() {
        if (clazz == null) {
            clazz = new ArrayList<Class>();
        }
        return this.clazz;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        if (space == null) {
            return "default";
        } else {
            return space;
        }
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

}
