//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.06 at 06:40:12 PM PDT 
//


package org.cihi.claml.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xhtml.InputType.class.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="xhtml.InputType.class">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="text"/>
 *     &lt;enumeration value="password"/>
 *     &lt;enumeration value="checkbox"/>
 *     &lt;enumeration value="radio"/>
 *     &lt;enumeration value="submit"/>
 *     &lt;enumeration value="reset"/>
 *     &lt;enumeration value="hidden"/>
 *     &lt;enumeration value="image"/>
 *     &lt;enumeration value="button"/>
 *     &lt;enumeration value="file"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "xhtml.InputType.class")
@XmlEnum
public enum XhtmlInputTypeClass {

    @XmlEnumValue("text")
    TEXT("text"),
    @XmlEnumValue("password")
    PASSWORD("password"),
    @XmlEnumValue("checkbox")
    CHECKBOX("checkbox"),
    @XmlEnumValue("radio")
    RADIO("radio"),
    @XmlEnumValue("submit")
    SUBMIT("submit"),
    @XmlEnumValue("reset")
    RESET("reset"),
    @XmlEnumValue("hidden")
    HIDDEN("hidden"),
    @XmlEnumValue("image")
    IMAGE("image"),
    @XmlEnumValue("button")
    BUTTON("button"),
    @XmlEnumValue("file")
    FILE("file");
    private final String value;

    XhtmlInputTypeClass(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static XhtmlInputTypeClass fromValue(String v) {
        for (XhtmlInputTypeClass c: XhtmlInputTypeClass.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
