
DROP TABLE HTMLPropertyVersion CASCADE CONSTRAINTS;

DROP TABLE BooleanPropertyVersion CASCADE CONSTRAINTS;

DROP TABLE PropertyVersion CASCADE CONSTRAINTS;

DROP TABLE ConceptPropertyVersion CASCADE CONSTRAINTS;

DROP TABLE StructureElementVersion CASCADE CONSTRAINTS;

DROP TABLE ElementVersion CASCADE CONSTRAINTS;

DROP TABLE Element CASCADE CONSTRAINTS;

DROP TABLE PropertyCategoryVersion CASCADE CONSTRAINTS;

DROP TABLE EnumeratedPropertyVersion CASCADE CONSTRAINTS;

DROP TABLE Enumeration CASCADE CONSTRAINTS;

DROP TABLE ValueDomainVersion CASCADE CONSTRAINTS;

DROP TABLE DataPropertyVersion CASCADE CONSTRAINTS;

DROP TABLE Class CASCADE CONSTRAINTS;

DROP TABLE NumericPropertyVersion CASCADE CONSTRAINTS;

DROP TABLE TextPropertyVersion CASCADE CONSTRAINTS;

DROP TABLE ValidationRuleVersion CASCADE CONSTRAINTS;

DROP TABLE StructureVersion CASCADE CONSTRAINTS;

DROP TABLE GraphicsPropertyVersion CASCADE CONSTRAINTS;

DROP TABLE SpecializationVersion CASCADE CONSTRAINTS;

DROP TABLE ConceptVersion CASCADE CONSTRAINTS;

DROP TABLE XMLPropertyVersion CASCADE CONSTRAINTS;

DROP TABLE Language CASCADE CONSTRAINTS;

DROP TABLE DateTimePropertyVersion CASCADE CONSTRAINTS;

DROP TABLE OtherPropertyVersion CASCADE CONSTRAINTS;

DROP TABLE URLPropertyVersion CASCADE CONSTRAINTS;

DROP TABLE CCIConceptVersion CASCADE CONSTRAINTS;

DROP TABLE CCIAttributeVersion CASCADE CONSTRAINTS;

DROP TABLE CCIComponentVersion CASCADE CONSTRAINTS;

DROP TABLE CCIGenericAttrVersion CASCADE CONSTRAINTS;

DROP TABLE CCIReferenceValueAttrVersion CASCADE CONSTRAINTS;
