//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.06 at 06:40:12 PM PDT 
//


package org.cihi.claml.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for xhtml.ruby.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xhtml.ruby.type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{}xhtml.ruby.content"/>
 *       &lt;attGroup ref="{}xhtml.ruby.common.attrib"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xhtml.ruby.type", propOrder = {
    "content"
})
public class XhtmlRubyType {

    @XmlElementRefs({
        @XmlElementRef(name = "rb", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rt", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rp", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rtc", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rbc", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Rt" is used by two different parts of a schema. See: 
     * line 51 of http://www.w3.org/MarkUp/SCHEMA/xhtml-ruby-1.xsd
     * line 48 of http://www.w3.org/MarkUp/SCHEMA/xhtml-ruby-1.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link XhtmlRbType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlRtcType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlRtType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlRbcType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlRpType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

}
