//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.06 at 06:40:12 PM PDT 
//


package org.cihi.claml.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for xhtml.map.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xhtml.map.type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{}xhtml.map.content"/>
 *       &lt;attGroup ref="{}xhtml.map.attlist"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xhtml.map.type", propOrder = {
    "h1OrH2OrH3"
})
public class XhtmlMapType implements XhtmlType{

    @XmlElementRefs({
        @XmlElementRef(name = "h2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "h6", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ins", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ol", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fieldset", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "area", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "h5", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "h3", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "form", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "h4", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pre", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "div", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "h1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ul", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "blockquote", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "script", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "noscript", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "p", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "del", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "table", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "hr", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "address", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> h1OrH2OrH3;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "lang")
    protected String nameAttribute;
    @XmlAttribute(name = "dir")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dir;
    @XmlAttribute(name = "title")
    protected String title;

    /**
     * Gets the value of the h1OrH2OrH3 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the h1OrH2OrH3 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getH1OrH2OrH3().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link XhtmlH2Type }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlH6Type }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlEditType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlOlType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlFieldsetType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlAreaType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlH5Type }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlH3Type }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlFormType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlH4Type }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlPreType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlDivType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlH1Type }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlUlType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlBlockquoteType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlScriptType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlNoscriptType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlDlType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlPType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlEditType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlTableType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlHrType }{@code >}
     * {@link JAXBElement }{@code <}{@link XhtmlAddressType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getH1OrH2OrH3() {
        if (h1OrH2OrH3 == null) {
            h1OrH2OrH3 = new ArrayList<JAXBElement<?>>();
        }
        return this.h1OrH2OrH3;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the nameAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameAttribute() {
        return nameAttribute;
    }

    /**
     * Sets the value of the nameAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameAttribute(String value) {
        this.nameAttribute = value;
    }

    /**
     * Gets the value of the dir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDir() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDir(String value) {
        this.dir = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

}
