//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.06 at 06:40:12 PM PDT 
//


package org.cihi.claml.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xhtml.Shape.Datatype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="xhtml.Shape.Datatype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="rect"/>
 *     &lt;enumeration value="circle"/>
 *     &lt;enumeration value="poly"/>
 *     &lt;enumeration value="default"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "xhtml.Shape.Datatype")
@XmlEnum
public enum XhtmlShapeDatatype {

    @XmlEnumValue("rect")
    RECT("rect"),
    @XmlEnumValue("circle")
    CIRCLE("circle"),
    @XmlEnumValue("poly")
    POLY("poly"),
    @XmlEnumValue("default")
    DEFAULT("default");
    private final String value;

    XhtmlShapeDatatype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static XhtmlShapeDatatype fromValue(String v) {
        for (XhtmlShapeDatatype c: XhtmlShapeDatatype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
